name: Production

on:
  push:
    branches: [ master ]

jobs:
  build_api:
    name: Build API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "{ \"insecure-registries\" : [\"${{ secrets.REGISTRY }}\"] }" | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
      - name: Build & Push
        uses: docker/build-push-action@v2.2.2
        with:
          tags: ${{ secrets.REGISTRY }}/hermes-api:latest
          push: true
      - name: Update
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            docker service update hermes-api --image ${{ secrets.REGISTRY }}/hermes-api:latest \
              --env-add SQLConnection="${{ secrets.SQL_CONNECTION }}" \
              --env-add Authentication__Secret="${{ secrets.AUTH_SECRET }}" \
              --env-add UIServer="${{ secrets.UI_SERVER }}"
