name: build-worker

on:
  push:
    branches: [ master ]
    paths:
      - './.github/workflows/build-worker.yaml'
      - 'hermes-worker/**'

jobs:
  build_api:
    name: Build Worker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "{ \"insecure-registries\" : [\"${{ secrets.REGISTRY }}\"] }" | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
      - name: Build & Push
        uses: docker/build-push-action@v2.2.2
        with:
          tags: ${{ secrets.REGISTRY }}/hermes-worker:latest
          file: ./hermes-worker/Dockerfile
          context: ./hermes-worker
          push: true