name: build-api

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/build-api.yaml'
      - 'hermes-api/**'

jobs:
  build_api:
    name: Build API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "{ \"insecure-registries\" : [\"${{ secrets.REGISTRY }}\"] }" | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
      - name: Build & Push
        uses: docker/build-push-action@v2.2.2
        with:
          tags: ${{ secrets.REGISTRY }}/hermes-api:latest
          file: ./hermes-api/Dockerfile
          context: ./hermes-api
          push: true
