name: deploy-worker

on:
  push:
    branches: [ master ]
    paths:
      - './.github/workflows/build-worker.yaml'
      - 'hermes-worker/**'

jobs:
  deploy_worker:
    name: Deploy Worker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Registry
        run: |
          echo "{ \"insecure-registries\" : [\"${{ secrets.REGISTRY }}\"] }" | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
      - name: Build & Push
        uses: docker/build-push-action@v2.2.2
        with:
          tags: ${{ secrets.REGISTRY }}/hermes-worker:latest
          file: ./hermes-worker/Dockerfile
          context: ./hermes-worker
          push: true
      - name: Update Service
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker service update \
              --image ${{ secrets.REGISTRY }}/hermes-worker:latest \
              hermes-worker